<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>GakumasCaptureEntrypoint</AssemblyName>
    <RootNamespace>GakumasCaptureEntrypoint</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
</Project>
